import { StyleSheet, Dimensions } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    // alignItems: "center",
  },
  title: {
    textAlign: "center",
    fontSize: Dimensions.get("window").width * 0.12,
    fontWeight: "bold",
    color: "#232B2B",
    fontFamily: "Avenir",
    marginTop: Dimensions.get("window").height / 5,
    marginBottom: Dimensions.get("window").height / 100,
  },
  slogan: {
    textAlign: "center",
    fontSize: Dimensions.get("window").width * 0.04,
    color: "gray",
    fontFamily: "Avenir",
    marginBottom: Dimensions.get("window").height / 30,
  },
  logo: {
    flex: 1,
    height: 120,
    width: 90,
    alignSelf: "center",
    margin: 30,
  },
  input: {
    height: 48,
    // borderRadius: 10,
    overflow: "hidden",
    backgroundColor: "white",
    marginTop: 10,
    marginBottom: 10,
    marginLeft: Dimensions.get("window").width / 9,
    marginRight: Dimensions.get("window").width / 9,
    paddingLeft: 16,
    borderColor: "#232B2B",
    borderBottomWidth: 0.5,
    fontFamily: "Avenir",
    // backgroundColor: "#F5F5F5",
  },
  button: {
    backgroundColor: "#232B2B",
    marginLeft: 30,
    marginRight: 30,
    marginTop: 20,
    height: 48,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonTitle: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
  footerView: {
    flex: 1,
    alignItems: "center",
    marginTop: 20,
  },
  footerText: {
    fontSize: 16,
    color: "#2e2e2d",
    fontFamily: "Avenir",
  },
  footerLink: {
    color: "#232B2B",
    fontWeight: "bold",
    fontSize: 16,
    fontFamily: "Avenir",
  },
  forgotPassword: {
    marginTop: Dimensions.get("window").height * 0.01,
    textAlign: "right",
    marginRight: Dimensions.get("window").width * 0.1,
    color: "gray",
    textDecorationLine: "underline",
  },
  modal: {
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 5,
  },
  modalTitle: {
    fontSize: Dimensions.get("window").width * 0.05,
    fontWeight: "bold",
    marginBottom: 10,
    fontFamily: "Avenir",
    marginTop: Dimensions.get("window").height * 0.01,
    fontFamily: "Avenir",
  },
  resetInstructions: {
    fontSize: Dimensions.get("window").width * 0.035,
    fontFamily: "Avenir",
    // marginTop: Dimensions.get("window").height * 0.01,
    marginBottom: Dimensions.get("window").height * 0.02,
    color: "gray",
  },
  modalInput: {
    height: Dimensions.get("window").height * 0.045,
    // borderColor: "#ccc",
    // borderWidth: 1,
    borderBottomWidth: 0.5,
    paddingHorizontal: 10,
    marginBottom: Dimensions.get("window").height * 0.03,
    fontFamily: "Avenir",
    marginRight: Dimensions.get("window").width * 0.03,
  },
  modalButtons: {
    flexDirection: "row",
    // justifyContent: "flex-end",
    justifyContent: "center",
  },
  modalButton: {
    paddingHorizontal: Dimensions.get("window").width * 0.05,
    paddingVertical: Dimensions.get("window").height * 0.01,
    marginLeft: Dimensions.get("window").width * 0.07,
    borderRadius: 4,
    backgroundColor: "#232B2B",
  },
  modalButtonTitleCancel: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: Dimensions.get("window").width * 0.035,
    fontFamily: "Avenir",
  },
  modalButtonTitle: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: Dimensions.get("window").width * 0.035,
    fontFamily: "Avenir",
  },
  modalCancelButton: {
    paddingHorizontal: Dimensions.get("window").width * 0.05,
    paddingVertical: Dimensions.get("window").height * 0.01,
    marginLeft: 10,
    borderRadius: 4,
    backgroundColor: "#fff",
    borderWidth: 1,
  },
  modalCancelButtonTitle: {
    color: "#000",
    fontWeight: "bold",
    fontSize: Dimensions.get("window").width * 0.035,
    fontFamily: "Avenir",
  },
});
