import { StyleSheet, Dimensions } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#fff",
  },
  title: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    marginBottom: 10,
    fontSize: 20,
    fontWeight: "semi-bold",
    color: "#2B2B2B",
    fontFamily: "Avenir",
  },
  logo: {
    flex: 1,
    height: 120,
    width: 90,
    alignSelf: "center",
    margin: 30,
  },
  input: {
    height: 48,
    overflow: "hidden",
    backgroundColor: "white",
    marginTop: 10,
    marginBottom: 10,
    marginLeft: Dimensions.get("window").width / 9,
    marginRight: Dimensions.get("window").width / 9,
    paddingLeft: 16,
    borderColor: "#232B2B",
    borderBottomWidth: 0.5,
    fontFamily: "Avenir",
  },
  button: {
    backgroundColor: "#232B2B",
    marginLeft: Dimensions.get("window").width / 9,
    marginRight: Dimensions.get("window").width / 9,
    marginTop: 20,
    height: 48,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonTitle: {
    color: "white",
    fontSize: 15,
    fontWeight: "bold",
    fontFamily: "Avenir",
  },
  footerView: {
    flex: 1,
    alignItems: "center",
    marginTop: 20,
  },
  footerText: {
    fontSize: 16,
    color: "gray",
    fontFamily: "Avenir",
  },
  footerLink: {
    color: "#232B2B",
    fontWeight: "bold",
    fontSize: 16,
  },
  containerConfirmation: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#fff",
  },
  titleConfirm: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    marginBottom: 10,
    fontSize: Dimensions.get("window").width * 0.07,
    fontWeight: "bold",
    color: "#2B2B2B",
    fontFamily: "Avenir",
  },
  buttonConfirm: {
    backgroundColor: "#232B2B",
    marginLeft: Dimensions.get("window").width / 9,
    marginRight: Dimensions.get("window").width / 9,
    marginTop: 20,
    height: 48,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: Dimensions.get("window").height * 0.2,
  },
  buttonTitleConfirm: {
    color: "white",
    fontSize: 15,
    fontWeight: "bold",
    fontFamily: "Avenir",
  },
});
