import { StyleSheet, Dimensions } from "react-native";
// import { color } from "react-native-elements/dist/helpers";

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#fff",
  },
  title: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 30,
    fontSize: 25,
    fontWeight: "bold",
    color: "#3b444c",
  },
  logo: {
    flex: 1,
    height: 120,
    width: 120,
    marginLeft: 30,
    margin: 30,
    borderRadius: 100,
  },
  button: {
    backgroundColor: "#04A78F",
    marginLeft: 30,
    marginRight: 30,
    marginTop: 20,
    height: 48,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  input: {
    height: 45,
    borderRadius: 10,
    borderColor: "lightgray",
    borderWidth: 1,
    overflow: "hidden",
    backgroundColor: "white",
    marginBottom: 10,
    marginLeft: 30,
    marginRight: 30,
    paddingLeft: 16,
  },
  savebutton: {
    backgroundColor: "#788eec",
    marginLeft: 150,
    marginRight: 150,
    marginTop: 20,
    height: 40,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonTitle: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
  textLabel: {
    fontSize: 15,
    color: "gray",
    marginBottom: 5,
    marginLeft: 30,
    marginTop: 10,
  },
  headline: {
    fontSize: 17,
    marginBottom: 10,
    color: "#3b444c",
    marginLeft: 30,
  },
  location: {
    fontSize: 17,
    color: "gray",
    marginBottom: 5,
    marginLeft: 30,
  },
  pencilbutton: {
    marginLeft: 150,
    marginRight: 150,
    marginTop: 20,
    height: 40,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonTitle: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
  headline: {
    fontSize: 17,
    marginBottom: 10,
    color: "#3b444c",
    marginLeft: 30,
  },
  location: {
    fontSize: 17,
    color: "gray",
    marginBottom: 5,
    marginLeft: 30,
  },
  listItem: {
    flexDirection: "row",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
    alignItems: "center",
  },
  avatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginRight: 10,
  },
  infoContainer: {
    justifyContent: "center",
    maxWidth: "50%",
  },
  name: {
    fontWeight: "bold",
    fontSize: 16,
    paddingLeft: 10,
  },
  occupation: {
    color: "gray",
    marginTop: 5,
    paddingLeft: 10,
    fontSize: Dimensions.get("window").width * 0.04,
  },
  town: {
    color: "gray",
    marginTop: 5,
    paddingLeft: 10,
    fontSize: Dimensions.get("window").width * 0.03,
  },

  // Navigation Bar at bottom of Screen
  containerNav: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    backgroundColor: "#fff",
    height: 90, // You can adjust the height as needed
    width: "100%",
    position: "absolute",
    bottom: 0,
    paddingBottom: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -10 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  tabButton: {
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  tabButtonIcon: {
    width: 30,
    height: 30,
  },
  tabButtonText: {
    fontSize: 12,
    color: "black",
    fontWeight: "bold",
    fontFamily: "Avenir",
  },
  tabButtonDisabledText: {
    fontSize: 12,
    color: "gray",
    fontFamily: "Avenir",
  },
  // end of Navigation Bar
  location: {
    fontSize: 17,
    color: "gray",
    marginBottom: 5,
    marginLeft: 30,
  },
  picker: {
    flex: 1,
    height: 50,
    // borderColor: '#04A78F',
    // borderWidth: 1,
    padding: 10,
    margin: 10,
    borderRadius: 5,
    backgroundColor: "white",
    marginLeft: 10,
  },
  pickerContainer: {
    padding: 10,
    margin: 10,
    marginLeft: 30,
  },
  pickerText: {
    height: Dimensions.get("window").width * 0.12,
    width: Dimensions.get("window").width - 60,
    borderColor: "lightgray",
    borderWidth: 1,
    borderRadius: 5,
    // borderBottomWidth: 1,
    // paddingBottom: 5,
    overflow: "hidden",
    backgroundColor: "white",
    marginBottom: 10,
    marginLeft: 30,
    marginRight: 20,
    paddingLeft: 16,
    color: "#C0C0C0",
    fontSize: 16,
    marginTop: Dimensions.get("window").height * 0.01,
  },
  tradeText: {
    marginLeft: 30,
    fontSize: 16,
    padding: 10,
    marginRight: 30,
    borderWidth: 1,
    borderBottomWidth: 1,
    borderBottomColor: "lightgray",
    borderColor: "lightgray",
    color: "black",
    marginBottom: 5,
    marginTop: 10,
  },
  settings: {
    alignItems: "center",
    justifyContent: "center",
    marginLeft: Dimensions.get("window").width * 0.05,
    fontSize: 30,
    fontWeight: "bold",
    color: "#3b444c",
    marginBottom: Dimensions.get("window").height * 0.02,
    marginTop: Dimensions.get("window").height * 0.02,
    fontFamily: "Avenir",
  },
  inputSettings: {
    height: 45,
    // borderRadius: 10,
    borderBottomWidth: 1,
    borderColor: "lightgray",
    // borderWidth: 1,
    overflow: "hidden",
    backgroundColor: "white",
    marginBottom: 10,
    marginLeft: 30,
    marginRight: 30,
    // paddingLeft: 16,
  },

  // Searcg Results FlatList
  avatarSearch: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginRight: 10,
    // marginTop: Dimensions.get("window").height * 0.02,
  },
  // listItemSearch: {
  //   flexDirection: "row",
  //   padding: 20,
  //   // borderBottomWidth: 1,
  //   // borderBottomColor: "#ccc",
  //   // borderWidth: 1,
  //   borderColor: "lightgray",
  //   // backgroundColor: "red",
  //   borderRadius: 20,
  //   marginBottom: Dimensions.get("window").height * 0.01,

  //   shadowColor: "#000",
  //   shadowOffset: { width: 0, height: 10 },
  //   shadowOpacity: 0.1,
  //   shadowRadius: 10,
  //   elevation: 10,
  //   position: "relative",

  // },
  infoContainerSearch: {
    justifyContent: "center",
  },
  nameSearch: {
    fontWeight: "bold",
    fontSize: 16,
    paddingLeft: 10,
  },
  occupationSearch: {
    color: "gray",
    marginTop: 5,
    paddingLeft: 10,
  },
});
