import { StyleSheet, Dimensions } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#fff",
  },
  title: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    marginBottom: 10,
    marginTop: 10,
    fontSize: 20,
    fontWeight: "semi-bold",
    color: "#3b444c",
    fontFamily: "Avenir",
  },
  input: {
    height: 45,
    // borderRadius: 10,
    borderColor: "#2B2B2B",
    borderBottomWidth: 0.5,
    overflow: "hidden",
    backgroundColor: "white",
    marginBottom: 10,
    marginLeft: Dimensions.get("window").width * 0.1,
    marginRight: Dimensions.get("window").width * 0.1,
    paddingLeft: 16,
    fontFamily: "Avenir",
    // backgroundColor: "#F5F5F5",
  },
  savebutton: {
    backgroundColor: "#2B2B2B",
    // marginLeft: 150,
    // marginRight: 150,
    marginTop: 20,
    height: 45,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
    width: Dimensions.get("window").width * 0.3,
    alignSelf: "center",
  },
  buttonTitle: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
    fontFamily: "Avenir",
  },
  textTopLabel: {
    fontSize: 15,
    color: "gray",
    marginBottom: 5,
    marginLeft: Dimensions.get("window").width * 0.1,
    marginTop: Dimensions.get("window").height * 0.03,
    fontFamily: "Avenir",
  },

  textLabel: {
    fontSize: 15,
    color: "gray",
    marginBottom: 5,
    marginLeft: Dimensions.get("window").width * 0.1,
    marginTop: 10,
    fontFamily: "Avenir",
  },
  headline: {
    fontSize: 17,
    marginBottom: 10,
    color: "#3b444c",
    marginLeft: 30,
    fontFamily: "Avenir",
  },
  location: {
    fontSize: 17,
    color: "gray",
    marginBottom: 5,
    marginLeft: 30,

    fontFamily: "Avenir",
  },
  picker: {
    height: 50,
    borderColor: "#04A78F",
    borderWidth: 1,
    padding: 10,
    margin: 10,
    backgroundColor: "white",
    marginLeft: 30,
    fontFamily: "Avenir",
  },
  pickerContainer: {
    padding: 10,
    margin: 10,
    marginLeft: 30,
    fontFamily: "Avenir",
  },
  dropdown: {
    marginBottom: Dimensions.get("window").height * 0.1,
  },
  pickerText: {
    marginLeft: 30,
    height: 45,
    borderBottomWidth: 0.5,
    // borderColor: "#2B2B2B",
    overflow: "hidden",
    backgroundColor: "white",
    marginBottom: 10,
    marginLeft: Dimensions.get("window").width * 0.1,
    marginRight: Dimensions.get("window").width * 0.1,
    paddingLeft: 16,
    fontFamily: "Avenir",
    // backgroundColor: "#F5F5F5",
  },
  exitButtonText: {
    color: "white",
    fontWeight: "bold",
    fontSize: 20,
    fontFamily: "Avenir",
  },
  image: {
    width: Dimensions.get("window").width * 0.38,
    height: Dimensions.get("window").width * 0.38,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: "#2B2B2B",
    marginTop: Dimensions.get("window").height * 0.02,
    borderColor: "#2B2B2B",
    alignContent: "center",
    alignSelf: "center",
  },
  mainWrapper: {
    paddingHorizontal: Dimensions.get("window").width * 0.07,
    paddingVertical: Dimensions.get("window").height * 0.01,
    backgroundColor: "#fff",
  },
  listContainer: {
    marginHorizontal: Dimensions.get("window").width * 0.06,
    paddingVertical: Dimensions.get("window").height * 0.01,
    backgroundColor: "#fff",
  },
  rowList: {
    backgroundColor: "#F5F5F5",
    marginBottom: Dimensions.get("window").height * 0.015,
    backgroundColor: "#fff",
    paddingBottom: Dimensions.get("window").height * 0.01,
    borderBottomColor: "#f5f5f5",
    borderBottomWidth: 1,
  },
  buttonConfirm: {
    backgroundColor: "#2B2B2B",
    marginLeft: 60,
    marginRight: 60,
    marginTop: 20,
    height: 48,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "Avenir",
  },
  containerConfirmation: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#fff",
  },
  titleConfirm: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 20,
    fontSize: Dimensions.get("window").width * 0.06,
    fontWeight: "bold",
    marginBottom: Dimensions.get("window").height * 0.02,
    // color: "white",
    // marginTop: 8,
    fontFamily: "Avenir",
  },
  subtitleConfirm: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 20,
    fontSize: Dimensions.get("window").width * 0.035,
    fontWeight: "bold",
    marginBottom: 20,
    color: "gray",
    fontFamily: "Avenir",
  },
});
